[2024-05-06 06:19:39,120] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.loading_data manual__2024-05-06T06:19:32.024048+00:00 [queued]>
[2024-05-06 06:19:39,125] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.loading_data manual__2024-05-06T06:19:32.024048+00:00 [queued]>
[2024-05-06 06:19:39,125] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 06:19:39,125] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-05-06 06:19:39,125] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 06:19:39,143] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): loading_data> on 2024-05-06 06:19:32.024048+00:00
[2024-05-06 06:19:39,147] {standard_task_runner.py:52} INFO - Started process 11854 to run task
[2024-05-06 06:19:39,149] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_Scoring_Data_Engineering_Pipeline', 'loading_data', 'manual__2024-05-06T06:19:32.024048+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_data_pipeline/.ipynb_checkpoints/lead_scoring_data_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmpn_cwvc46', '--error-file', '/tmp/tmp8v_jsxke']
[2024-05-06 06:19:39,150] {standard_task_runner.py:80} INFO - Job 71: Subtask loading_data
[2024-05-06 06:19:39,190] {task_command.py:371} INFO - Running <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.loading_data manual__2024-05-06T06:19:32.024048+00:00 [running]> on host 9eefda8bbe39
[2024-05-06 06:19:39,250] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_Scoring_Data_Engineering_Pipeline
AIRFLOW_CTX_TASK_ID=loading_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-06T06:19:32.024048+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-06T06:19:32.024048+00:00
[2024-05-06 06:19:39,251] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/Lead_scoring_data_pipeline/utils.py", line 95, in load_data_into_db
    data = pd.read_csv(os.path.join(DATA_DIRECTORY, LEAD_SCORING_CSV), index_col=[0])
NameError: name 'LEAD_SCORING_CSV' is not defined
[2024-05-06 06:19:39,253] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Lead_Scoring_Data_Engineering_Pipeline, task_id=loading_data, execution_date=20240506T061932, start_date=20240506T061939, end_date=20240506T061939
[2024-05-06 06:19:39,271] {standard_task_runner.py:92} ERROR - Failed to execute job 71 for task loading_data (name 'LEAD_SCORING_CSV' is not defined; 11854)
[2024-05-06 06:19:39,281] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-06 06:19:39,310] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
