[2024-05-06 06:18:26,569] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.loading_data manual__2024-05-06T06:18:14.247957+00:00 [queued]>
[2024-05-06 06:18:26,575] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.loading_data manual__2024-05-06T06:18:14.247957+00:00 [queued]>
[2024-05-06 06:18:26,575] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 06:18:26,575] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2024-05-06 06:18:26,575] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 06:18:26,596] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): loading_data> on 2024-05-06 06:18:14.247957+00:00
[2024-05-06 06:18:26,602] {standard_task_runner.py:52} INFO - Started process 11672 to run task
[2024-05-06 06:18:26,605] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_Scoring_Data_Engineering_Pipeline', 'loading_data', 'manual__2024-05-06T06:18:14.247957+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_data_pipeline/.ipynb_checkpoints/lead_scoring_data_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmp92cchcpo', '--error-file', '/tmp/tmpufyzlpk_']
[2024-05-06 06:18:26,606] {standard_task_runner.py:80} INFO - Job 69: Subtask loading_data
[2024-05-06 06:18:26,658] {task_command.py:371} INFO - Running <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.loading_data manual__2024-05-06T06:18:14.247957+00:00 [running]> on host 9eefda8bbe39
[2024-05-06 06:18:26,702] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_Scoring_Data_Engineering_Pipeline
AIRFLOW_CTX_TASK_ID=loading_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-06T06:18:14.247957+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-06T06:18:14.247957+00:00
[2024-05-06 06:18:26,703] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/Lead_scoring_data_pipeline/utils.py", line 95, in load_data_into_db
    data = pd.read_csv(os.path.join(DATA_DIRECTORY, LEAD_SCORING_CSV), index_col=[0])
NameError: name 'LEAD_SCORING_CSV' is not defined
[2024-05-06 06:18:26,706] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=Lead_Scoring_Data_Engineering_Pipeline, task_id=loading_data, execution_date=20240506T061814, start_date=20240506T061826, end_date=20240506T061826
[2024-05-06 06:18:26,721] {standard_task_runner.py:92} ERROR - Failed to execute job 69 for task loading_data (name 'LEAD_SCORING_CSV' is not defined; 11672)
[2024-05-06 06:18:26,736] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-06 06:18:26,792] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
