[2024-05-06 06:18:19,325] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.loading_data manual__2024-05-06T06:18:14.247957+00:00 [queued]>
[2024-05-06 06:18:19,330] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.loading_data manual__2024-05-06T06:18:14.247957+00:00 [queued]>
[2024-05-06 06:18:19,330] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 06:18:19,330] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-05-06 06:18:19,330] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 06:18:19,349] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): loading_data> on 2024-05-06 06:18:14.247957+00:00
[2024-05-06 06:18:19,353] {standard_task_runner.py:52} INFO - Started process 11649 to run task
[2024-05-06 06:18:19,355] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_Scoring_Data_Engineering_Pipeline', 'loading_data', 'manual__2024-05-06T06:18:14.247957+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_data_pipeline/.ipynb_checkpoints/lead_scoring_data_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmpea5zoywi', '--error-file', '/tmp/tmpp3jmb8bw']
[2024-05-06 06:18:19,356] {standard_task_runner.py:80} INFO - Job 68: Subtask loading_data
[2024-05-06 06:18:19,398] {task_command.py:371} INFO - Running <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.loading_data manual__2024-05-06T06:18:14.247957+00:00 [running]> on host 9eefda8bbe39
[2024-05-06 06:18:19,453] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_Scoring_Data_Engineering_Pipeline
AIRFLOW_CTX_TASK_ID=loading_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-06T06:18:14.247957+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-06T06:18:14.247957+00:00
[2024-05-06 06:18:19,454] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/Lead_scoring_data_pipeline/utils.py", line 95, in load_data_into_db
    data = pd.read_csv(os.path.join(DATA_DIRECTORY, LEAD_SCORING_CSV), index_col=[0])
NameError: name 'LEAD_SCORING_CSV' is not defined
[2024-05-06 06:18:19,457] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Lead_Scoring_Data_Engineering_Pipeline, task_id=loading_data, execution_date=20240506T061814, start_date=20240506T061819, end_date=20240506T061819
[2024-05-06 06:18:19,473] {standard_task_runner.py:92} ERROR - Failed to execute job 68 for task loading_data (name 'LEAD_SCORING_CSV' is not defined; 11649)
[2024-05-06 06:18:19,487] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-06 06:18:19,507] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
