[2024-05-06 05:10:13,079] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables manual__2024-05-06T05:10:08.886493+00:00 [queued]>
[2024-05-06 05:10:13,084] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables manual__2024-05-06T05:10:08.886493+00:00 [queued]>
[2024-05-06 05:10:13,084] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 05:10:13,084] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-05-06 05:10:13,084] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 05:10:13,119] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): encoding_categorical_variables> on 2024-05-06 05:10:08.886493+00:00
[2024-05-06 05:10:13,126] {standard_task_runner.py:52} INFO - Started process 3944 to run task
[2024-05-06 05:10:13,130] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_training_pipeline', 'encoding_categorical_variables', 'manual__2024-05-06T05:10:08.886493+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_training_pipeline/.ipynb_checkpoints/lead_scoring_training_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmp5c3jki11', '--error-file', '/tmp/tmp_1_lepos']
[2024-05-06 05:10:13,130] {standard_task_runner.py:80} INFO - Job 47: Subtask encoding_categorical_variables
[2024-05-06 05:10:13,184] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables manual__2024-05-06T05:10:08.886493+00:00 [running]> on host 9eefda8bbe39
[2024-05-06 05:10:13,266] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_training_pipeline
AIRFLOW_CTX_TASK_ID=encoding_categorical_variables
AIRFLOW_CTX_EXECUTION_DATE=2024-05-06T05:10:08.886493+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-06T05:10:08.886493+00:00
[2024-05-06 05:10:13,266] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/Lead_scoring_training_pipeline/utils.py", line 56, in encode_features
    conn = sqlite3.connect(DB_PATH+DB_FILE_NAME)
sqlite3.OperationalError: unable to open database file
[2024-05-06 05:10:13,270] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Lead_scoring_training_pipeline, task_id=encoding_categorical_variables, execution_date=20240506T051008, start_date=20240506T051013, end_date=20240506T051013
[2024-05-06 05:10:13,296] {standard_task_runner.py:92} ERROR - Failed to execute job 47 for task encoding_categorical_variables (unable to open database file; 3944)
[2024-05-06 05:10:13,341] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-06 05:10:13,396] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
